version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.5
      - test-2.7
jobs:
  test-3.6: &test-template
    environment:
      COLUMNS: 160
      # default is /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PATH: ~/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    docker:
      - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            pip install -q --user --upgrade -r requirements.txt

      - run:
          name: List deps
          command: |
            mkdir -p artifacts
            pip freeze | tee artifacts/pip-freeze.txt

      - run:
          name: setup.py develop
          command: |
            python setup.py develop --prefix ~/.local --no-deps

      - run:
          name: Run tests
          command: |
            make tests-coverage-single-nocontracts

      - run:
          name: Example draw maps
          command: |
            make tests-maps-coverage

      - run:
          name: Example LFV download
          command: |
            rm test-data/LFV.json
            wget https://github.com/duckietown/duckietown-world/raw/master18/test-data/LFV.json -O test-data/LFV.json

      - run:
          name: Example LFV
          command: |
            make tests-LFV-coverage

      - run:
          name: Coverage analysis
          when: always
          command: |
            make coverage-report

      - run:
          name: Coveralls submission
          when: always
          command: |
            make coverage-coveralls

      - run:
          name: Create JUnit output
          when: always
          command: |
            make junit

      - test-results-store:
          path: out-comptests/junit

      - store_artifacts:
          path: out-comptests/duckietown_world_tests
          destination: duckietown_world_tests
          
      - store_artifacts:
          path: artifacts
          destination: artifacts

      - store_artifacts:
          path: out_coverage
          destination: coverage
  test-3.5:
    <<: *test-template
    docker:
      - image: python:3.5
  test-2.7:
    <<: *test-template
    docker:
    - image: python:2.7
  test-3.7:
    <<: *test-template
    docker:
    - image: python:3.7
  test-circle-2.7:
    <<: *test-template
    docker:
    - image: circle/python
